console.log('🔧 AZURE REDIRECT URI UPDATE NEEDED');
console.log('');
console.log('Current redirect URI in Azure:');
console.log('❌ http://localhost:3010/api/auth/callback/azure-ad');
console.log('');
console.log('Add this NEW redirect URI in Azure portal:');
console.log('✅ http://10.10.200.103:3010/api/auth/callback/azure-ad');
console.log('');
console.log('WHY THIS FIXES THE ISSUE:');
console.log('- Cookies sometimes don\'t work properly with "localhost"');
console.log('- Using the actual IP address resolves cookie domain issues');
console.log('- The Network address shown in your dev server is: 10.10.200.103:3010');
console.log('');
console.log('STEPS:');
console.log('1. Go to Azure portal → App registrations → Your app');
console.log('2. Click "Authentication"');
console.log('3. Add this redirect URI: http://10.10.200.103:3010/api/auth/callback/azure-ad');
console.log('4. Keep the localhost one as well for backup');
console.log('5. Save the configuration');
console.log('');
console.log('THEN TEST USING:');
console.log('http://10.10.200.103:3010/auth/signin');
console.log('(instead of localhost)');