console.log('🔍 HOW TO NAVIGATE TO REDIRECT URI SETTINGS IN AZURE PORTAL');
console.log('');
console.log('STEP-BY-STEP NAVIGATION:');
console.log('');
console.log('1. Go to: https://portal.azure.com');
console.log('2. Sign in with your Microsoft account');
console.log('3. In the search bar at the top, type: "App registrations"');
console.log('4. Click on "App registrations" from the search results');
console.log('5. Find your app in the list (should show your app name)');
console.log('6. Click on your app name to open it');
console.log('7. In the left sidebar menu, click "Authentication"');
console.log('8. Look for the "Redirect URIs" section');
console.log('9. Click "+ Add a platform" if no platforms exist');
console.log('10. Select "Web" as the platform type');
console.log('11. Add this exact URL: http://localhost:3010/api/auth/callback/azure-ad');
console.log('12. Click "Configure" or "Save"');
console.log('');
console.log('ALTERNATIVE PATH:');
console.log('1. Go to: https://portal.azure.com');
console.log('2. Click "Azure Active Directory" (or "Microsoft Entra ID")');
console.log('3. Click "App registrations" in the left menu');
console.log('4. Find and click your app');
console.log('5. Click "Authentication" in left menu');
console.log('6. Add the redirect URI as above');
console.log('');
console.log('WHAT TO LOOK FOR:');
console.log('- Your app name or Client ID: aae7d797-379a-4a62-a8f9-5b164c3f9f3e');
console.log('- Section called "Redirect URIs" or "Reply URLs"');
console.log('- Platform type should be "Web"');
console.log('');
console.log('ADD THIS EXACT URL:');
console.log('http://localhost:3010/api/auth/callback/azure-ad');